### Выход пользователя
POST http://localhost:8080/auth/logout
Content-Type: application/json
Cookie: fg_id=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxfQ.TNxs-v-4rE88DaH3VIVHifVpqHh8c1zqJW1Glxc3Ky0
